// Bundles the in-iframe harness (+ @khiye/checkers/browser + @khiye/shared)
// into a single minified IIFE, emitted as a string module the assembler injects.
// Run: pnpm --filter @khiye/preview build:harness
import { build } from "esbuild";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const result = await build({
  entryPoints: [join(root, "src/harness/harness.ts")],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  minify: true,
  write: false,
  legalComments: "none",
});

const code = result.outputFiles[0].text;
const out = `// GENERATED by scripts/build-harness.mjs — do not edit by hand.
// Run \`pnpm --filter @khiye/preview build:harness\` to regenerate.
export const HARNESS_JS: string = ${JSON.stringify(code)};
export const HARNESS_BYTES = ${Buffer.byteLength(code)};
`;
writeFileSync(join(root, "src/harness-bundle.ts"), out);
console.log(`✓ harness bundled: ${(Buffer.byteLength(code) / 1024).toFixed(1)} KB`);
